const modal=document.getElementById('modal'),modalCard=document.getElementById('modalCard');
function openModal(html){modalCard.innerHTML=html;modal.classList.remove('hidden')}
function closeModal(){modal.classList.add('hidden');modalCard.innerHTML=''}
modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});
function openCheckout(){
  const a=agent(state.currentAgentId),lines=cartLines(),sum=lines.reduce((s,x)=>s+x.qty*x.p.price,0);
  openModal(`<div class="modal-head"><div><span class="kicker">Review stock order</span><h2>Checkout</h2></div><button class="icon-btn" id="modalClose">×</button></div>
    <div class="form-grid"><div class="field full"><label>Delivery address</label><textarea id="checkoutAddress">${esc(a.address)}</textarea></div><div class="field full"><label>Order note (optional)</label><textarea id="checkoutNotes" placeholder="Delivery or packing note"></textarea></div></div>
    <div class="summary-lines">${lines.map(x=>`<div class="summary-line"><span>${x.qty} × ${esc(x.p.name)}</span><strong>${money.format(x.qty*x.p.price)}</strong></div>`).join('')}<div class="summary-line total"><span>Total</span><strong>${money.format(sum)}</strong></div></div>
    <div class="payfast-box"><div class="payfast-word">Pay<span>Fast</span></div><p>The live build will redirect the agent to PayFast and update the order from PayFast’s payment notification. This prototype simulates a successful confirmation.</p><button id="simulatePay" class="primary-btn">Simulate successful PayFast payment</button></div>`);
  document.getElementById('modalClose').onclick=closeModal;
  document.getElementById('simulatePay').onclick=()=>completeDemoPayment();
}
function completeDemoPayment(){
  const address=document.getElementById('checkoutAddress').value.trim(),notes=document.getElementById('checkoutNotes').value.trim(),lines=cartLines();if(!address){showToast('Delivery address is required');return}
  const order={id:`ORD-${new Date().toISOString().slice(2,10).replaceAll('-','')}-${String(Math.floor(Math.random()*9000)+1000)}`,agentId:state.currentAgentId,createdAt:nowIso(),status:'Paid',payment:'Paid',courier:'',tracking:'',address,notes,items:lines.map(x=>({productId:x.p.id,qty:x.qty,price:x.p.price}))};
  state.orders.unshift(order);state.cart={};const a=agent(state.currentAgentId);a.address=address;a.lastOrder=order.createdAt.slice(0,10);save();updateCartBadge();closeModal();showToast(`${order.id} paid and sent to Alcare`);navigate('myorders');
}

function renderMyOrders(){const list=state.orders.filter(o=>o.agentId===state.currentAgentId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));main.innerHTML=`<div class="page">${pageHead('Order history','My orders','See payment, processing and dispatch status without contacting the office.')}${list.map(o=>renderOrderCard(o)).join('')||'<div class="empty">No orders yet.</div>'}</div>`}
function renderOrderCard(o){return `<article class="order-card"><div class="order-top"><div><strong>${o.id}</strong><div class="product-meta">${dateLabel(o.createdAt)}</div></div><span class="status ${statusClass(o.status)}">${esc(o.status)}</span></div><div class="order-items">${o.items.map(i=>`${i.qty} × ${esc(product(i.productId)?.name||'Product')}`).join(' • ')}</div><div class="order-foot"><span>${o.tracking?`Tracking: <strong>${esc(o.tracking)}</strong>`:'Tracking added when dispatched'}</span><strong>${money.format(total(o))}</strong></div></article>`}
function renderAccount(){const a=agent(state.currentAgentId);main.innerHTML=`<div class="page">${pageHead('Agent account','My account','These details are reused for every stock order and can be updated by the agent.')}
  <div class="panel"><form id="accountForm" class="form-grid"><div class="field"><label>Name</label><input name="name" value="${esc(a.name)}"></div><div class="field"><label>Business / trading name</label><input name="business" value="${esc(a.business)}"></div><div class="field"><label>Email</label><input name="email" value="${esc(a.email)}"></div><div class="field"><label>Phone</label><input name="phone" value="${esc(a.phone)}"></div><div class="field"><label>Town</label><input name="town" value="${esc(a.town)}"></div><div class="field"><label>Province</label><input name="province" value="${esc(a.province)}"></div><div class="field full"><label>Default delivery address</label><textarea name="address">${esc(a.address)}</textarea></div><div class="field full"><div class="form-actions"><button class="primary-btn">Save account</button></div></div></form></div></div>`;document.getElementById('accountForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));Object.assign(a,d);save();showToast('Account saved');renderApp()}}

function renderDashboard(){const paid=state.orders.filter(o=>o.payment==='Paid'),month=paid.filter(o=>o.createdAt.slice(0,7)==='2026-09'),rev=month.reduce((s,o)=>s+total(o),0),open=paid.filter(o=>!['Completed','Cancelled'].includes(o.status)).length;const activeAgents=state.agents.filter(a=>a.active).length;main.innerHTML=`<div class="page">${pageHead('Alcare office','Dashboard','What needs attention, plus a quick view of reseller activity.',`<button class="primary-btn" onclick="navigate('orders')">View orders</button>`)}
<div class="stats-grid"><div class="stat-card"><span>September sales</span><strong>${money.format(rev)}</strong><small>${month.length} paid orders</small></div><div class="stat-card"><span>Open fulfilment</span><strong>${open}</strong><small>Paid orders not completed</small></div><div class="stat-card"><span>Active agents</span><strong>${activeAgents}</strong><small>${state.agents.length} total accounts</small></div><div class="stat-card"><span>Catalogue</span><strong>${state.products.filter(p=>p.active).length}</strong><small>Active products</small></div></div>
<div class="two-col"><div class="panel"><h2>Orders needing attention</h2>${paid.filter(o=>!['Completed','Cancelled'].includes(o.status)).slice(0,6).map(renderOrderCardAdmin).join('')||'<div class="empty">Nothing needs attention.</div>'}</div><div class="panel"><h2>Sales signals</h2><div class="insight-grid" style="grid-template-columns:1fr"><div class="insight-card"><h3>Inactive reseller</h3><p>${state.agents.filter(a=>daysSince(a.lastOrder)>60).map(a=>a.name).join(', ')||'No inactivity flags'} — no recent stock order.</p></div><div class="insight-card"><h3>Current top product</h3><p>${esc(topProducts()[0]?.name||'No data')} leads demo revenue across recorded orders.</p></div><div class="insight-card"><h3>Catalogue control</h3><p>Alcare can change prices, activate/deactivate products and add new lines without a developer deployment.</p></div></div></div></div></div>`}
function renderOrderCardAdmin(o){const a=agent(o.agentId);return `<article class="order-card"><div class="order-top"><div><strong>${o.id}</strong><div class="product-meta">${esc(a?.name||'Agent')} • ${dateLabel(o.createdAt)}</div></div><span class="status ${statusClass(o.status)}">${esc(o.status)}</span></div><div class="order-items">${o.items.length} lines • ${o.items.reduce((s,i)=>s+i.qty,0)} units</div><div class="order-foot"><button class="small-btn" onclick="openOrder('${o.id}')">Open order</button><strong>${money.format(total(o))}</strong></div></article>`}
function daysSince(date){return Math.floor((Date.now()-new Date(date+'T00:00:00Z'))/86400000)}

