from pathlib import Path
import base64,re

ROOT=Path('perfect-women-start-here')

def b64(src,dst):
    dst.write_text(base64.b64encode(src.read_bytes()).decode())

p=ROOT/'dev_sources/pw-training-sequence-v5.js'
s=p.read_text()
start=s.index('function strengthModal(session){')
end=s.index('function finishStrength(session,log){',start)
new=r'''function strengthSetDone(exlog,count){for(let i=0;i<count;i++)if(!(exlog.sets[i]&&exlog.sets[i].done))return false;return true}
function strengthEnsureSets(exlog,count){while(exlog.sets.length<count)exlog.sets.push({weight:'',reps:'',done:false})}
function strengthPreviousText(prev,target){if(!prev)return '';const val=target.t==='seconds'?`${prev.reps||'—'} sec`:(target.w?`${prev.weight||'—'} kg × ${prev.reps||'—'}`:`${prev.reps||'—'} reps`);return val}
function guidedRest(session,log,setIndex){
  stopTimers();const m=ensureModal(),body=m.querySelector('#pwSequenceBody'),exlog=log.exercises[activeEx],target=session.ex[activeEx],base=session.sets.min,required=base+(exlog.optionalChosen?1:0),doneExercise=strengthSetDone(exlog,required),nextSet=doneExercise?-1:exlog.sets.findIndex((x,i)=>i<required&&!x.done),nextExercise=activeEx<log.exercises.length-1?session.ex[activeEx+1]:null;let sec=+log.rest||session.rest[0];m.classList.add('on');
  const nextCopy=!doneExercise?`Next: Set ${nextSet+1} — ${target.n}`:nextExercise?`Next exercise: ${nextExercise.n}`:'Next: Finish session';
  body.innerHTML=`<header class="pw-train-head"><button id="pwSeqClose" aria-label="Close">×</button><div><small>WEEK ${session.w} · SESSION ${session.s}</small><b>${esc(session.name)}</b></div><span>REST</span></header><section class="pw-guided-rest"><div class="pw-rest-check">✓</div><small>SET ${setIndex+1} COMPLETE</small><h1>${esc(target.n)}</h1><div class="pw-rest-big" id="pwGuidedRestTime">${sec}s</div><p>${esc(nextCopy)}</p><div class="pw-rest-actions"><button id="pwGuidedSkip">SKIP REST</button><button id="pwGuidedPlus">+15 SEC</button></div></section>`;
  let ended=false;function finish(){if(ended)return;ended=true;if(restTimer)clearInterval(restTimer);restTimer=null;strengthModal(session)}
  body.querySelector('#pwSeqClose').onclick=()=>{if(restTimer)clearInterval(restTimer);restTimer=null;putSeq(session.track,session.w,session.s,log);closeModal()};body.querySelector('#pwGuidedSkip').onclick=finish;body.querySelector('#pwGuidedPlus').onclick=()=>{sec+=15;body.querySelector('#pwGuidedRestTime').textContent=sec+'s'};
  restTimer=setInterval(()=>{sec--;const el=body.querySelector('#pwGuidedRestTime');if(el)el.textContent=sec+'s';if(sec<=0)finish()},1000)
}
function strengthModal(session){
  stopTimers();const log=newStrengthLog(session);activeEx=Math.min(activeEx,log.exercises.length-1);const ex=log.exercises[activeEx],target=session.ex[activeEx],prev=priorExercise(session.track,ex.name,session.w,session.s),m=ensureModal(),body=m.querySelector('#pwSequenceBody');m.classList.add('on');const min=session.sets.min,max=session.sets.max;if(ex.sets.length>min)ex.optionalChosen=true;const needed=min+(ex.optionalChosen?1:0);strengthEnsureSets(ex,needed);let nextSet=-1;for(let i=0;i<needed;i++){if(!ex.sets[i].done){nextSet=i;break}}const complete=nextSet<0,hasOptional=max>min&&!ex.optionalChosen;const setSummary=ex.sets.slice(0,needed).map((x,i)=>`<span class="${x.done?'done':''}">SET ${i+1}${x.done?' ✓':''}</span>`).join('');
  const head=`<header class="pw-train-head"><button id="pwSeqClose" aria-label="Close">×</button><div><small>WEEK ${session.w} · SESSION ${session.s}</small><b>${esc(session.name)}</b></div><span id="pwSeqElapsed">${fmtElapsed(log.startedAt)}</span></header><div class="pw-train-progress"><i style="width:${((activeEx+1)/log.exercises.length)*100}%"></i></div>${session.guide?`<details class="pw-session-guide"><summary>VIEW APPROVED SESSION GUIDE</summary><img src="${esc(session.guide)}" alt="${esc(session.name)} approved workout guide"></details>`:''}`;
  if(complete){
    const nextName=activeEx<log.exercises.length-1?session.ex[activeEx+1].n:'';body.innerHTML=head+`<section class="pw-ex-card pw-ex-complete"><div class="pw-ex-count">EXERCISE ${activeEx+1} OF ${log.exercises.length}</div><div class="pw-rest-check">✓</div><h1>${esc(ex.name)} complete</h1><p class="pw-ex-cue">${esc(target.c||'')}</p><div class="pw-set-summary">${setSummary}</div>${hasOptional?`<button id="pwSeqOptional" class="pw-optional-set">+ ADD OPTIONAL SET ${min+1}</button>`:''}${nextName?`<div class="pw-next-preview"><small>NEXT EXERCISE</small><b>${esc(nextName)}</b></div>`:'<div class="pw-next-preview"><small>ALL EXERCISES COMPLETE</small><b>Finish this session</b></div>'}</section><footer class="pw-train-nav"><button id="pwSeqPrev" ${activeEx===0?'disabled':''}>← PREVIOUS</button><button id="pwSeqNext" class="primary">${activeEx===log.exercises.length-1?'FINISH SESSION':'START NEXT EXERCISE →'}</button></footer>`;
    body.querySelector('#pwSeqClose').onclick=()=>{putSeq(session.track,session.w,session.s,log);closeModal()};const opt=body.querySelector('#pwSeqOptional');if(opt)opt.onclick=()=>{ex.optionalChosen=true;strengthEnsureSets(ex,min+1);putSeq(session.track,session.w,session.s,log);strengthModal(session)};body.querySelector('#pwSeqPrev').onclick=()=>{activeEx--;strengthModal(session)};body.querySelector('#pwSeqNext').onclick=()=>{putSeq(session.track,session.w,session.s,log);if(activeEx<log.exercises.length-1){activeEx++;strengthModal(session)}else finishStrength(session,log)};startElapsed(log);return;
  }
  const cur=ex.sets[nextSet],last=strengthPreviousText(prev,target),lastHelp=prev&&target.w?'Repeat this or increase slightly if the last set felt controlled.':'';
  body.innerHTML=head+`<section class="pw-ex-card pw-guided-set"><div class="pw-ex-count">EXERCISE ${activeEx+1} OF ${log.exercises.length}</div><h1>${esc(ex.name)}</h1><p class="pw-ex-cue">${esc(target.c||'')}</p><p class="pw-prescription">${esc(session.sets.label)} · target ${esc(target.r)}</p>${last?`<div class="pw-last-time"><small>LAST TIME</small><b>${esc(last)}</b>${lastHelp?`<span>${esc(lastHelp)}</span>`:''}</div>`:''}<div class="pw-set-summary">${setSummary}</div><div class="pw-current-set"><small>SET ${nextSet+1} OF ${needed}${ex.optionalChosen&&nextSet===min?' · OPTIONAL':''}</small><div class="pw-current-inputs ${target.w?'':'no-weight'}">${target.w?`<label>KG<input id="pwGuidedWeight" inputmode="decimal" type="number" min="0" step="0.5" value="${esc(cur.weight)}" placeholder="kg"></label>`:''}<label>${target.t==='seconds'?'SECONDS':'REPS'}<input id="pwGuidedReps" inputmode="numeric" type="number" min="0" step="1" value="${esc(cur.reps)}" placeholder="${target.t==='seconds'?'sec':'reps'}"></label></div><button id="pwGuidedDone" class="pw-set-complete-btn">COMPLETE SET ${nextSet+1}</button></div></section><div class="pw-rest-choice"><span>REST AFTER THIS SET</span>${session.rest.map(x=>`<button data-rest="${x}" class="${+log.rest===x?'on':''}">${x}s</button>`).join('')}</div><footer class="pw-train-nav"><button id="pwSeqPrev" ${activeEx===0?'disabled':''}>← PREVIOUS EXERCISE</button><button class="primary" disabled>COMPLETE SET TO CONTINUE</button></footer>`;
  function pull(){const w=body.querySelector('#pwGuidedWeight'),r=body.querySelector('#pwGuidedReps');if(w)cur.weight=w.value;if(r)cur.reps=r.value;putSeq(session.track,session.w,session.s,log)}
  body.querySelector('#pwSeqClose').onclick=()=>{pull();closeModal()};body.querySelector('#pwGuidedWeight')?.addEventListener('change',pull);body.querySelector('#pwGuidedReps').addEventListener('change',pull);body.querySelectorAll('[data-rest]').forEach(btn=>btn.onclick=()=>{pull();log.rest=+btn.dataset.rest;putSeq(session.track,session.w,session.s,log);body.querySelectorAll('[data-rest]').forEach(x=>x.classList.toggle('on',x===btn))});body.querySelector('#pwSeqPrev').onclick=()=>{pull();activeEx--;strengthModal(session)};body.querySelector('#pwGuidedDone').onclick=()=>{pull();if(!String(cur.reps||'').trim()){body.querySelector('#pwGuidedReps').focus();return}cur.done=true;putSeq(session.track,session.w,session.s,log);guidedRest(session,log,nextSet)};startElapsed(log)
}
'''
s=s[:start]+new+s[end:]
p.write_text(s)
b64(p,ROOT/'asset_sources/pw-training-sequence-v5.b64')

# Guided flow CSS
cp=ROOT/'dev_sources/pw-training-sequence-v5.css'
css=cp.read_text()
if 'guided strength flow' not in css:
    css += r'''
/* guided strength flow */
.pw-guided-set{padding-bottom:14px}.pw-prescription{font-weight:900;color:#075568;margin:5px 0 12px}.pw-last-time{display:grid;gap:2px;background:#edfafa;border:1px solid #cce9eb;border-radius:13px;padding:11px 13px;margin:10px 0}.pw-last-time small{font-size:10px;letter-spacing:.09em;font-weight:900;color:#f06f61}.pw-last-time b{font-size:17px;color:#075568}.pw-last-time span{font-size:12px;color:#5d797f}.pw-set-summary{display:flex;flex-wrap:wrap;gap:6px;margin:10px 0}.pw-set-summary span{border-radius:999px;background:#eef4f4;color:#73888d;padding:6px 9px;font-size:10px;font-weight:900}.pw-set-summary span.done{background:#dff4e7;color:#28764a}.pw-current-set{border:2px solid #08a8b5;border-radius:17px;padding:14px;background:#f4fdfd}.pw-current-set>small{display:block;font-weight:900;letter-spacing:.08em;color:#f06f61;margin-bottom:10px}.pw-current-inputs{display:grid;grid-template-columns:1fr 1fr;gap:9px}.pw-current-inputs.no-weight{grid-template-columns:1fr}.pw-current-inputs label{font-size:10px;font-weight:900;color:#075568;letter-spacing:.06em}.pw-current-inputs input{display:block;width:100%;box-sizing:border-box;margin-top:5px;min-height:52px;border:1px solid #bcdfe2;border-radius:12px;background:white;padding:10px 12px;font-size:20px;font-weight:900;color:#075568}.pw-set-complete-btn{width:100%;margin-top:12px;min-height:50px;border:0;border-radius:13px;background:#f06f61;color:#fff;font-weight:900;font-size:14px}.pw-guided-rest{min-height:68vh;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:22px}.pw-rest-check{width:58px;height:58px;border-radius:50%;display:grid;place-items:center;background:#dff4e7;color:#2f8b54;font-size:30px;font-weight:900;margin:0 auto 8px}.pw-guided-rest small{font-weight:900;letter-spacing:.1em;color:#f06f61}.pw-guided-rest h1{margin:6px 0 10px;color:#075568;font-size:26px}.pw-rest-big{font-size:64px;line-height:1;font-weight:900;color:#075568;margin:14px 0}.pw-guided-rest p{font-weight:800;color:#4c6d74;font-size:15px}.pw-rest-actions{display:flex;gap:9px;margin-top:12px}.pw-rest-actions button{border:0;border-radius:999px;padding:11px 15px;background:#edfafa;color:#075568;font-weight:900}.pw-ex-complete{text-align:center}.pw-ex-complete .pw-ex-cue{text-align:left}.pw-optional-set{width:100%;border:2px dashed #08a8b5;border-radius:13px;background:#f4fdfd;color:#075568;font-weight:900;padding:12px;margin:8px 0 12px}.pw-next-preview{display:grid;gap:3px;background:#fff4c2;border-radius:13px;padding:12px 14px;text-align:left;margin-top:10px}.pw-next-preview small{font-size:10px;font-weight:900;color:#f06f61;letter-spacing:.08em}.pw-next-preview b{color:#075568;font-size:16px}@media(max-width:420px){.pw-rest-big{font-size:54px}.pw-guided-rest{min-height:62vh}.pw-current-inputs input{font-size:18px}.pw-train-nav button{min-height:48px}}
'''
cp.write_text(css)
b64(cp,ROOT/'asset_sources/pw-training-sequence-v5.css.b64')

# cache bump
sp=ROOT/'dev_sources/sw-v3.js'
sw=sp.read_text();sw=re.sub(r"const C='pw8-v[^']+';","const C='pw8-v9-guided-strength';",sw);sp.write_text(sw);b64(sp,ROOT/'asset_sources/sw.js.b64')

assert 'function guidedRest(session,log,setIndex)' in p.read_text()
assert 'COMPLETE SET TO CONTINUE' in p.read_text()
print('guided strength flow patched')
